version: 2
project_name: website-operator
dist: bin/
release:
  skip_upload: true
builds:
  - id: website-operator
    env:
      - CGO_ENABLED=0
    main: ./cmd/website-operator
    binary: website-operator
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cybozu-go/website-operator.Version={{.Version}}
  - id: website-operator-ui
    env:
      - CGO_ENABLED=0
    main: ./cmd/website-operator-ui
    binary: website-operator-ui
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cybozu-go/website-operator.Version={{.Version}}
  - id: repo-checker
    env:
      - CGO_ENABLED=0
    main: ./cmd/repo-checker
    binary: repo-checker
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cybozu-go/website-operator.Version={{.Version}}
before:
  hooks:
    - make frontend
dockers_v2:
  - id: website-operator
    dockerfile: ./Dockerfile
    ids:
      - website-operator
    extra_files:
      - LICENSE
    images:
      - "ghcr.io/cybozu-go/website-operator"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
    flags:
      - "--target=website-operator"
  - id: website-operator-ui
    dockerfile: ./Dockerfile
    ids:
      - website-operator-ui
    extra_files:
      - LICENSE
      - ui/frontend/dist
    images:
      - "ghcr.io/cybozu-go/website-operator-ui"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
    flags:
      - "--target=ui"
  - id: repo-checker
    dockerfile: ./Dockerfile
    ids:
      - repo-checker
    extra_files:
      - LICENSE
    images:
      - "ghcr.io/cybozu-go/repo-checker"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
    flags:
      - "--target=repo-checker"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "dev"
changelog:
  use: github-native
