name: Setup aqua and tools
description: Setup aqua and tools for CI workflows.
inputs:
  save-cache:
    description: |
      If true, the action will save the cache after installing all tools.
      If false, the action skips saving the cache, but restores the cache if it exists.
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Restore aqua caches (restoring cache only)
      if: ${{ inputs.save-cache == 'false' }}
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
        restore-keys: |
          v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
    - name: Restore aqua caches (saving cache is enabled)
      if: ${{ inputs.save-cache != 'false' }}
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
        restore-keys: |
          v1-aqua-installer-${{runner.os}}-${{runner.arch}}
    - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
      with:
        aqua_version: v2.59.0 # renovate: aquaproj/aqua
        aqua_opts: ${{ case(inputs.save-cache != 'false', '', '-l')}}
