name: Frontend CI

on:
  workflow_call:

jobs:
  ui:
    name: Build UI frontend
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml
      - uses: flatt-security/setup-takumi-guard-npm@6d4182745c1e474c35a023573c2612c085be45a4 # v1.2.0
        with:
          bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - run: make frontend
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: website-operator-ui
          path: |
            ui/frontend/dist
          if-no-files-found: error
