name: Pinact
on:
  pull_request:
    paths:
      - '.github/**'
      - 'aqua.yaml'
      - 'aqua-checksums.json'
jobs:
  verify-pinact:
    name: Verify pinned GitHub Actions comments
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-aqua
      - name: Verify SHAs and tag comments are consistent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pinact run --check --verify-comment
